import { AppError } from "@/lib/errors";
import { serverEnvSchema } from "@/lib/env/schema";

const parsedServerEnv = serverEnvSchema.safeParse({
  NODE_ENV: process.env.NODE_ENV,
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
  SUPABASE_STORAGE_BUCKET: process.env.SUPABASE_STORAGE_BUCKET,
  SUPABASE_ASSET_IMAGES_BUCKET: process.env.SUPABASE_ASSET_IMAGES_BUCKET,
  SUPABASE_MAINTENANCE_ATTACHMENTS_BUCKET:
    process.env.SUPABASE_MAINTENANCE_ATTACHMENTS_BUCKET,
  SUPABASE_COMPLIANCE_DOCUMENTS_BUCKET: process.env.SUPABASE_COMPLIANCE_DOCUMENTS_BUCKET,
  DOCUMENT_UPLOAD_MAX_SIZE_BYTES: process.env.DOCUMENT_UPLOAD_MAX_SIZE_BYTES,
  CRON_SECRET: process.env.CRON_SECRET,
  EMAIL_PROVIDER: process.env.EMAIL_PROVIDER,
  EMAIL_FROM: process.env.EMAIL_FROM,
  RESEND_API_KEY: process.env.RESEND_API_KEY,
  UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
  UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
  RATE_LIMIT_KEY_SALT: process.env.RATE_LIMIT_KEY_SALT,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
  STRIPE_STARTER_PRICE_ID: process.env.STRIPE_STARTER_PRICE_ID,
  STRIPE_SMALL_FLEET_PRICE_ID: process.env.STRIPE_SMALL_FLEET_PRICE_ID,
  STRIPE_GROWING_FLEET_PRICE_ID: process.env.STRIPE_GROWING_FLEET_PRICE_ID,
});

if (!parsedServerEnv.success) {
  throw new AppError("CONFIGURATION_ERROR", "Server environment variables are invalid.", {
    cause: parsedServerEnv.error.flatten().fieldErrors,
  });
}

export const serverEnv = parsedServerEnv.data;

export const isSupabaseServerConfigReady = Boolean(
  serverEnv.NEXT_PUBLIC_SUPABASE_URL && serverEnv.SUPABASE_SERVICE_ROLE_KEY,
);
